//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Downloader.rc
//
#define ID_CANCEL                       1
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_DOWNLOADER                  173
#define IDD_DUMMY                       179
#define IDR_TORRENT1                    180
#define IDI_LOGO                        182
#define IDB_LOGO                        192
#define IDR_TORRENT_MENU                193
#define IDR_TORRENT                     193
#define IDD_CONNECTION_INFO             194
#define IDI_INFO                        202
#define IDC_TAB2                        999
#define IDC_TAB                         1000
#define IDC_TORRENT_PROGRESS            1001
#define IDC_PROGRESS                    1001
#define IDC_TORRENT_PROGRESS_TEXT       1002
#define IDC_SCRAPE_SEEDS_TEXT           1003
#define IDC_SCRAPE_LEECHERS_TEXT        1004
#define IDC_BUTTON1                     1005
#define IDC_REMOTEADMIN_CHANGEPASSWORD_BUTTON 1005
#define IDC_TORRENT_BLOCKSCOMPLETE_TEXT 1005
#define IDC_HISTORY_BUTTON              1005
#define IDC_CHECK1                      1006
#define IDC_REMOTEADMIN_ENABLE_CHECK    1006
#define IDC_TORRENT_BLOCKSINCOMPLETE_TEXT 1006
#define IDC_MAXUPLOADRATEUNLIMITED_CHECK 1006
#define IDC_INCOMPLETE_BUTTON           1006
#define IDC_ENABLE_CHECK                1006
#define IDC_DEFAULT_BUTTON              1006
#define IDC_1000_CHECK                  1006
#define IDS_UPLOADED                    1006
#define IDC_EDIT1                       1007
#define IDC_REMOTEADMIN_PORT_EDIT       1007
#define IDC_NEWPASSWORD_EDIT            1007
#define IDC_MAXACTIVETORRENTS_EDIT      1007
#define IDC_TORRENT_BLOCKSPARTIAL_TEXT  1007
#define IDC_MASTERIP_EDIT               1007
#define IDS_STATUS_TEXT                 1007
#define IDC_REMOTEADMINISTRATION_GROUP  1008
#define IDC_EDIT3                       1008
#define IDC_CHOKEUPDATEINTERVAL_EDIT    1008
#define IDC_TORRENT_BLOCKSTOTAL_TEXT    1008
#define IDS_DOWNLOADED                  1008
#define IDC_REMOTEADMIN_PORT_STATIC     1009
#define IDC_EDIT4                       1009
#define IDC_MAXUPLOADS_EDIT             1009
#define IDS_DOWNLOAD_RATE               1009
#define IDC_EDIT2                       1010
#define IDC_VERIFYPASSWORD_EDIT         1010
#define IDC_MINCLIENTS_EDIT             1010
#define IDS_UPLOADED_RATE               1010
#define IDC_SPIN1                       1011
#define IDC_MAXACTIVETORRENTS_SPIN      1011
#define IDC_INCOMPLETE_EDIT             1011
#define IDC_DEFAULT_EDIT                1011
#define IDC_SPIN2                       1012
#define IDC_CHOKEUPDATEINTERVAL_SPIN    1012
#define IDC_SPIN3                       1013
#define IDC_MAXUPLOADS_SPIN             1013
#define IDC_SPIN4                       1014
#define IDC_MINCLIENTS_SPIN             1014
#define IDC_SCRAPEUPDATEINTERVAL_EDIT   1015
#define IDC_CHECK2                      1015
#define IDC_DOUBLEBLOCKMAP_CHECK        1015
#define IDC_DONTUSEDEFAULTPATH_CHECK    1015
#define IDC_0002_CHECK                  1015
#define IDC_CHECK_AUTOEXEC              1015
#define IDC_SPIN5                       1016
#define IDC_SCRAPEUPDATEINTERVAL_SPIN   1016
#define IDC_MAXUPLOADRATE_EDIT          1017
#define IDS_PROGRESS_TEXT               1017
#define IDC_MAXUPLOADRATE_SPIN          1018
#define IDC_UPNPENABLE_CHECK            1019
#define IDC_PORT_EDIT                   1020
#define IDC_REMOTEADMIN_PORT_SPIN       1020
#define IDC_PORT_SPIN                   1021
#define IDC_HISTORY_EDIT                1021
#define IDC_UPNPPORTRANGEMIN_EDIT       1022
#define IDC_CONNECTION_COMBO            1022
#define IDC_UPNPPORTRANGEMIN_SPIN       1023
#define IDC_TORRENTCLOSETONOTIFY_CHECK  1023
#define IDC_UPNPPORTRANGEMAX_EDIT       1024
#define IDC_PRIORITY_LIST               1024
#define IDS_PATH_TEXT                   1024
#define IDC_UPNPPORTRANGEMAX_SPIN       1025
#define IDC_MOVEUP_BUTTON               1027
#define IDC_MOVEDOWN_BUTTON             1028
#define IDC_CHECK3                      1029
#define IDC_SENDSTOPONCLOSE_CHECK       1029
#define IDC_USETABS_CHECK               1029
#define IDC_0004_CHECK                  1029
#define IDS_ESTIMATED_TIME              1029
#define IDC_MASTER_RADIO                1030
#define IDC_SLAVE_RADIO                 1031
#define IDC_SEQUENTIAL_RADIO            1033
#define IDC_RAREST_RADIO                1034
#define IDC_RANDOM_RADIO                1035
#define IDC_DEFAULT_STATIC              1036
#define IDC_0008_CHECK                  1037
#define IDC_0010_CHECK                  1038
#define IDC_0020_CHECK                  1039
#define IDC_0040_CHECK                  1040
#define IDC_0080_CHECK                  1041
#define IDC_0100_CHECK                  1042
#define IDC_0200_CHECK                  1043
#define IDC_0400_CHECK                  1044
#define IDC_0800_CHECK                  1045
#define IDC_2000_CHECK                  1046
#define IDC_CHECK5                      1047
#define IDC_4000_CHECK                  1047
#define IDC_MULTILINETABS_CHECK         1047
#define IDC_CHECK4                      1048
#define IDC_BUTTONTABS_CHECK            1048
#define IDC_LOGO                        1049
#define IDC_CLIENT_LIST                 1051
#define ID_FILE_EXIT                    32771
#define ID_TORRENT_TEMP                 32773
#define ID_TOOLS_OPTIONS                32775
#define ID_HELP_ABOUT                   32777
#define ID_TORRENT_SHOWSTATUSWINDOW     32778
#define ID_TORRENT_UNLOAD               32779
#define ID_TORRENT_REMOVETORRENT        32780
#define ID_NOTIFICATION_EXIT            32782
#define ID_NOTIFICATION_RESTORE         32783
#define ID_TORRENTNOTIFICATION_RESTORE  32784
#define ID_TORRENT_PAUSE                32785
#define ID_TORRENT_RESUME               32786
#define ID_TORRENT_PRIORITIZETORRENTS   32787
#define ID_TORRENT_PRIORITIZE           32788
#define ID_TORRENT_HIDESTATUSWINDOW     32789
#define ID_FILE_SETFILEPRIORITY         32790
#define ID_FILE_CLUSTER                 32791
#define ID_VIEW_CUSTOMIZEOVERVIEW       32792
#define ID_VIEW_CUSTOMIZECLIENTLIST     32794
#define ID_BUTTON32795                  32795
#define ID_BUTTON32796                  32796
#define ID_CONNECTIONINFO               32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
